### PR TITLE
No unicode update

### PR DESCRIPTION
**Pull request by ocots**
- Seems that `->` does not work. I have let `=>`.
- I have added `in` equivalent to `∈`.
- We have:

```julia
julia> @def o begin
               z in R, variable
               t in [ 0, 1 ], time
               x in R^2, state
               u in R, control
               r = x1
               v = x2
               0 <= r(0) - z <= 1,            (1)
               0 <= v(1)^2 <= 1,              (2)
               [ 0, 0 ] <= x(0) <= [ 1, 1 ],  (♡)
               z >= 0,                        (3)
               derivative(x)(t) == [ v(t), r(t)^2 + z ]
               integral( u(t)^2 + z * x1(t) ) => min
           end
ERROR: ParsingError: 
Line 8: (0 ≤ v(1) ^ 2 ≤ 1, 2)
bad constraint declaration
```

because of `v = x2`. Do we accept this kind of aliases? It means that we need `x1`, `x2`, ..., automatically.

### CODE REVIEW

**Comment by ocots** [comment]
It seems that we have `x[1]`, `x[2]` available instead of `x1`, `x2`...

**Comment by ocots** [comment]
This works now:

```julia
    @def o begin
        z in R^2, variable
        t in [ 0, 1 ], time
        x in R^2, state
        u in R^2, control
        r = x1
        v = x2
        0 <= r(0) - z1 <= 1,            (1)
        0 <= v(1)^2 <= 1,               (2)
        [ 0, 0 ] <= x(0) <= [ 1, 1 ],   (♡)
        z1 >= 0,                        (3)
        z2 == 1
        u2(t) == 0
        derivative(x)(t) == [ v(t), r(t)^2 + z1 ]
        integral( u1(t)^2 + z1 * x1(t) ) => min
    end
```

**Comment by ocots** [comment]
@jbcaillau Please review and merge.

**Comment by jbcaillau** [comment]
> @jbcaillau Please review and merge.

thanks:
- yes, `x[i]`'s are automatic aliases (up to any dim)
- `=>` was already in merged main (and in doc), checking there are no conflicts 🤞🏾
- nice for `in` (missed it)

**Comment by ocots** [comment]
> > @jbcaillau Please review and merge.
> 
> thanks:
> 
> * yes, `x[i]`'s are automatic aliases (up to any dim)

Yes I figured it out. I have added `xi`. Ok?

> * `=>` was already in merged main (and in doc), checking there are no conflicts 🤞🏾

It seems ok. Too bad that `->` is not working. 

> * nice for `in` (missed it)

👍

**Comment by jbcaillau** [comment]
> > * yes, `x[i]`'s are automatic aliases (up to any dim)
> 
> Yes I figured it out. I have added `xi`. Ok?
>
> > * nice for `in` (missed it)
> 
> 👍

Good. Check https://github.com/control-toolbox/OptimalControl.jl/pull/299

**Pull request merged**
