### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ocots**

### CODE REVIEW

**Comment by jbcaillau** [comment]
ouh la 🫢...

**Comment by ocots** [comment]
I have just changed the readme. The fail is for covering.

**Comment by ocots** [comment]
I have just changed the readme. The fail is for covering. The target is 90% see https://github.com/control-toolbox/CTBase.jl/blob/main/.github/codecov.yml

**Comment by jbcaillau** [comment]
@ocots yes, indeed. mind-boggling commit 🙃

**Review by jbcaillau — COMMENTED** [review]
✅

**Pull request merged**
