### PR TITLE
refactoring + add getters and setters

### PR DESCRIPTION
**Pull request by ocots**
I have made some modifications. I have added getters for a solution but I have also renamed getters for a model. It is clearer for me with the prefix `get_`. I have thus updated the `Project.toml`.

I will take a look at https://github.com/control-toolbox/CTBase.jl/issues/144#issuecomment-2288393413.

I have also restructured the code to simplify in the future documentation, the organisation of the presentation the model, the solution and their setters and getters.

@PierreMartinon @jbcaillau Please comment.

### CODE REVIEW

**Comment by ocots** [comment]
@jbcaillau We should make the `v0.12.5` release before merging this PR.

**Comment by jbcaillau** [comment]
> @jbcaillau We should make the `v0.12.5` release before merging this PR.

👍🏽 go ahead!

**Comment by ocots** [comment]
> > @jbcaillau We should make the `v0.12.5` release before merging this PR.
> 
> 👍🏽 go ahead!

Done!

**Comment by ocots** [comment]
In the future documentation, if we use the getters, then, we will have something like:

```julia
sol = solve(ocp)
x = get_state(sol)
```

Do we prefer:

```julia
sol = solve(ocp)
x = state(sol)
```

Here is the list of getters:

```julia
# OptimalControlModel

get_dim_control_constraints
get_dim_state_constraints
get_dim_mixed_constraints
get_dim_path_constraints
get_dim_boundary_constraints
get_dim_variable_constraints
get_dim_control_range
get_dim_state_range,
get_dim_variable_range
get_model_expression
get_initial_time
get_initial_time_name
get_final_time
get_final_time_name
get_time_name
get_control_dimension
get_control_components_names
get_control_name
get_state_dimension
get_state_components_names
get_state_name
get_variable_dimension
get_variable_components_names
get_variable_name
get_lagrange
get_mayer
get_criterion
get_dynamics

# in the previous getters, some are common with OptimalControlSolution

# OptimalControlSolution

get_times
get_control
get_state, get_variable
get_costate
get_objective
get_iterations
get_stopping
get_message
get_success
get_infos
```

**Comment by ocots** [comment]
The most used by the user I guess are those on an `OptimalControlSolution`. Maybe, we can keep `_get` for those on an `OptimalControlModel` and for the others:

```julia
times    # or time_grid since times is very common
control # this will be used to define also some control law. Will be there any conflict?
state
variable
costate
objective
iterations
stopping
message
success
infos
```

If we have that, not clear to write something like: `success = success(sol)` or `state = state(sol)`.

Usually we would write:

```julia
times = time_grid(sol)
u = control(sol)
x = state(sol)
v = variable(sol)
p = costate(sol)
obj = objective(sol)
Niter = iterations(sol)
stopping # ??
message # ??
success # ??
infos # ??
```

**Comment by ocots** [comment]
@PierreMartinon @jbcaillau Please make a comment.

**Comment by jbcaillau** [comment]
> @PierreMartinon @jbcaillau Please make a comment.

Thanks @ocots I like this best: 
```julia
times = time_grid(sol)
u = control(sol)
x = state(sol)
v = variable(sol)
p = costate(sol)
obj = objective(sol)
Niter = iterations(sol)
...
```
- actually, does it make sense (and is it a good / common practice in Julia) to use `field(sol)` for the getter, and `field!(sol, val)` for the setter?
- in the end, if there are not clear choice, we can also keep the two with aliases (`state = get_state`, *etc.*)

**Comment by ocots** [comment]
If you have several types, getters are a good idea. We just have one but with getters we can make some checkings, some computations, etc.

Maybe we can have both as you said with aliases.

We can make the aliases inside OptimalControl.jl and let in CTBase.jl the functiins with `get_`.

**Comment by ocots** [comment]
@jbcaillau @PierreMartinon I will rename some getters to have something like 

```julia
times = time_grid(sol)
u = control(sol)
x = state(sol)
v = variable(sol)
p = costate(sol)
obj = objective(sol)
Niter = iterations(sol)
...
```

**Comment by ocots** [comment]
I have removed all the prefixes `get_`.

I make a push soon.

**Pull request merged**
