### PR TITLE
WIP REPL

### PR DESCRIPTION
**Pull request by ocots**
I have fixed some bugs.

But I don't see how to handle the parsing of the dynamics. Actually, 

```julia
ẋ(t) == 1
```

is parsed as a constraint. It would have been nice to parse it as a dynamics to avoid to store multiple definition.

### CODE REVIEW

**Comment by ocots** [comment]
I have taken into account this: https://github.com/control-toolbox/CTBase.jl/pull/76

**Comment by jbcaillau** [comment]
@ocots You have to keep track of the names of the time and state (it is a bit more than pre-parsing, but you need it) and do a [guarded match](https://thautwarm.github.io/MLStyle.jl/latest/syntax/pattern.html#guards) once you have built the *dotted name* of the state (check unicode stuff on this in `onepass.jl`):
```julia
@match e begin
    ...
    :( $y($s) == e_ ) && if ((y == dx) && (s == t)) end => ...
```

**Comment by ocots** [comment]
I have made a simple REPL "parsing". I take any expression and try to parse the updated code with the macro `@def`. If it works I push the new expression, otherwise I don't.  I just have added to store only unique expression:

```julia
unique!(push!(model[:any], e))
```

**Review by jbcaillau — APPROVED** [review]
@ocots thanks. merging and testing

**Pull request merged**
