### PR TITLE
corrected some comments in constraint_type

### PR DESCRIPTION
**Pull request by jbcaillau**
for the record:
- eventually not simplifying and keeping matching on `u(t0)`like expressions to effectively forbid them when mixed with correct things, as in `x(t)+u(t0)` (that would otherwise be analysed as `:state_range`)
- added / corrected some comments

### CODE REVIEW

**Comment by jbcaillau** [comment]
@ocots please merge

**Comment by jbcaillau** [comment]
🙏🏽 is such cases, good to delete branch + close issue (not automatic in `GitHub`)

**Comment by ocots** [comment]
I am with the phone. Don't see where to delete the branch. I check.

**Comment by jbcaillau** [comment]
> I am with the phone. Don't see where to delete the branch. I check.

✅ already done it

**Pull request merged**
