### PR TITLE
287 dev avoid generic types in struct

### PR DESCRIPTION
**Pull request by ocots**

### CODE REVIEW

**Comment by ocots** [comment]
@jbcaillau can you have a look?

**Review by jbcaillau — COMMENTED** [review]
@ocots what does v2 to v4 change do?

**Comment by ocots** [comment]
> @ocots what does v2 to v4 change do?

v2 is deprecated and not accepted anymore. No run with v2. But with v4, we have a bug :-(

**Comment by ocots** [comment]
@jbcaillau I have:

- made parametric types for callable types;
- reviewed the constructors with DataTypes.

**Comment by jbcaillau** [comment]
> @jbcaillau can you have a look?

@ocots busy these days, sorry I could not have a finer look at this. regarding what we discussed, if adding the `{<:Function, ...}` type parameter does not complicate too much calling the construction (we want to avoid sth like `Cons{type of(f), ...}(f)`!), fine.

**Pull request merged**
