### PR TITLE
Constraint index

### PR DESCRIPTION
**Pull request by jbcaillau**
@joseph-gergaud introduced a specific type for integer ranges to avoid dispatch problems when the user does not enforce `Real` type for bounds. Check this:
```julia
julia> constraint!(ocp, :initial, 2:3, [ 0, 0 ])
julia> constraint!(ocp, :final, Index(1), 0)
julia> constraint!(ocp, :initial, 2:3, [ 0, 0 ], [1, 2])
julia> constraint!(ocp, :final, Index(1), 0, 2)
julia> constraint!(ocp, :control, Index(1), 0, 2)
julia> constraint!(ocp, :state, 2:3, [ 0, 0 ], [1, 2])
```

### CODE REVIEW

**Review by ocots — COMMENTED** [review]
ok pour moi

**Comment by joseph-gergaud** [comment]
ok

**Comment by jbcaillau** [comment]
@ocots quick review + MR please?

**Review by ocots — COMMENTED** [review]
Nickel !

**Pull request merged**
