### PR TITLE
replaced OptimalControlInit with updated _OptimalControlInit

### PR DESCRIPTION
**Pull request by PierreMartinon**
Ok, here we are, you can review the changes.

We should be able to test this one with pre-release 0.9.0 of CTDirect that corresponds to the v0.9.0 branch.

- [x] check tests from CTDirect using local dev'd versions for both packages
- [x] check tests from OptimalControl using local dev'd versions for both packages

### CODE REVIEW

**Comment by PierreMartinon** [comment]
@ocots @jbcaillau Trying to test from *OptimalControl*
The versions requirements on *main* seem very old oO ?

```
[compat]
CTBase = "0.9"
CTDirect = "0.6"
CTFlows = "0.3"
CTProblems = "0.5"
julia = "1.8"
```

**Comment by ocots** [comment]
@PierreMartinon Just a remark. I understand why you have added an `_` to `OptimalControlInit` but we have many types which are internal such as `OptimalControlSolution` which has no underscore I guess.

**Comment by jbcaillau** [comment]
> @ocots @jbcaillau Trying to test from _OptimalControl_ The versions requirements on _main_ seem very old oO ?
> 
> ```
> [compat]
> CTBase = "0.9"
> CTDirect = "0.6"
> CTFlows = "0.3"
> CTProblems = "0.5"
> julia = "1.8"
> ```

@PierreMartinon Check what is planned in https://github.com/control-toolbox/OptimalControl.jl/pull/192#issuecomment-2199983718

@ocots it is true that the changes in the `compat` do not appear (my 💩 with `reverse`?)

**Comment by ocots** [comment]
> @ocots @jbcaillau Trying to test from _OptimalControl_ The versions requirements on _main_ seem very old oO ?
> 
> ```
> [compat]
> CTBase = "0.9"
> CTDirect = "0.6"
> CTFlows = "0.3"
> CTProblems = "0.5"
> julia = "1.8"
> ```

Yes we have to update `OptimalControl.jl`. It is quite difficult to test with packages which are on top.

**Comment by PierreMartinon** [comment]
> > > @ocots @jbcaillau Trying to test from _OptimalControl_ The versions requirements on _main_ seem very old oO ?
> > > ```
> > > [compat]
> > > CTBase = "0.9"
> > > CTDirect = "0.6"
> > > CTFlows = "0.3"
> > > CTProblems = "0.5"
> > > julia = "1.8"
> > > ```
> > 
> > 
> > Yes we have to update `OptimalControl.jl`. It is quite difficult to test with packages which are on top.
> 
> @ocots A bit tricky: can you please take care of it 😬?

Tests seem fine on this branch https://github.com/control-toolbox/OptimalControl.jl/pull/193
I made a draft PR to show the changes

Some details on the init part at the end: [git push --set-upstream origin update_ctdirect0.9_ctbasexx](https://github.com/control-toolbox/CTDirect.jl/pull/137)
I have no particular opinion on using _ or not, do as you prefer ;-)

**Comment by PierreMartinon** [comment]
I see the underscore was quietly murdered :D 
I'll update CTDirect accordingly for 0.9.1

**Comment by ocots** [comment]
Yes I have removed the underscore :-)

**Pull request merged**
